---
# $ fly -t target sp -p hello-world -c concourse.yml
resources:
- name: src-git
  type: git
  source:
    #uri: https://github.com/wdstar/concourse-examples
    uri: https://gitlab.io.example.com/concourse/examples.git
    paths:
    - hello-world
    branch: master
    skip_ssl_verification: true
  #check_every: 1h  # default: 1m

jobs:
- name: say-hello
  plan:
  - get: src-git
    params:
      depth: 5
    trigger: true
  - task: say-hello
    file: src-git/hello-world/say-hello.yml
