---
# $ fly -t target sp -p image-build00 -c concourse.yml -l ~/credentials-test.yml
resources:
- name: src-git
  type: git
  source:
    uri: https://gitlab.io.example.com/concourse/examples.git
    branch: master
    paths:
    - image-build00
    # for the internal CA signed server certificate
    skip_ssl_verification: true
- name: docker-reg
  type: docker-image
  source:
    repository: gitlab.io.example.com:5050/concourse/examples/image-build00
    #tag: 0.0.1  # default: latest
    # ((param)) style: fly >= 3.2.0
    username: ((docker-id))
    password: ((docker-pw))
    registry_mirror: https://((registry-mirror-domain))
    ca_certs:
    - domain: gitlab.io.example.com:5050
      cert: ((docker-reg-ca-cert))
    - domain: ((registry-mirror-domain))
      cert: ((docker-reg-ca-cert))
- name: alpine-latest
  type: docker-image
  source:
    repository: alpine
    registry_mirror: https://((registry-mirror-domain))
    ca_certs:
    - domain: ((registry-mirror-domain))
      cert: ((docker-reg-ca-cert))

jobs:
- name: build-img
  plan:
  - get: src-git
    trigger: true
  - get: alpine-latest
  - task: ci-build
    file: src-git/image-build00/ci/build.yml
    # for testing typically.
    image: alpine-latest  # overrides the task's image_reosurce.
  - put: docker-reg
    params:
      build: docker-build  # <- src-git/image-build00/ci/build.yml
      #build: src-git/image-build00
      tag: src-git/image-build00/tag
      tag_as_latest: true  # default: false
    get_params:
      #skip_download: true  # default: false
      skip_download: false  # set false for the following ci-test task.
  - task: ci-test
    file: src-git/image-build00/ci/test.yml
    image: docker-reg  # overrides the task's image_reosurce.
- name: img-updated
  plan:
  - get: docker-reg
    params:
      skip_download: true
    trigger: true
  - get: alpine-latest
  - task: update-message
    image: alpine-latest
    config:
      platform: linux
      run:
        path: /bin/sh
        args:
        - -c
        - |
          sleep 5s
          echo 'image-build00 image updated!'
